---
Name: form-extras
After: 
- 'framework/*'
- 'cms/*'
---
FormField:
  extensions:
    - 'TooltipFieldExtension'
FormExtraJquery:
  # Version can be: framework, v1 or v2
  jquery_version: 'framework'
  jquery_migrate: 'auto'
  jquery_ui_version: 'framework'
  jquery_ui_theme: 'default'
BaseUploadField:
  use_subsite_integration: true
ImageUploadField:
  # default size in MB
  default_max_file_size: 4
  default_allowed_extensions: [jpg,jpeg,png,gif]
CMSMain:
  extensions:
    - 'HasOneEditUpdateFormExtension'
GridFieldDetailForm_ItemRequest:
  extensions:
    - 'HasOneEditUpdateFormExtension'
DataObject:
  extensions:
    - 'HasOneEditDataObjectExtension'
ChosenField:
  rtl: false
Select2Field:
  rtl: false
  use_v3: false
SexyPasswordField:
  show_password_constraints: true
  enable_show_hide: true
SimpleTinyMceField:
  menubar: false
  skin: 'light'
  toolbar: 'cut copy paste undo redo | removeformat | nulllist numlist blockquote | alignleft aligncenter alignright | formatselect | bold italic textcolor hr | link image media'
  plugins: 'autolink autoresize link lists hr anchor image media paste textcolor emoticons'
CropboxField:
  use_hammer: true
  use_mousewheel: true
Image:
  extensions: 
    - 'CropboxImage'
LeftAndMain:
  extensions:
    - FormExtraLeftAndMainExtension
