---
Name: form-extras
After: 
- 'framework/*'
- 'cms/*'
---
BaseUploadField:
  use_subsite_integration: true
ImageUploadField:
  # default size in MB
  default_max_file_size: 4
  default_allowed_extensions: [jpg,jpeg,png,gif]
CMSMain:
  extensions:
    - 'HasOneEditUpdateFormExtension'
GridFieldDetailForm_ItemRequest:
  extensions:
    - 'HasOneEditUpdateFormExtension'
DataObject:
  extensions:
    - 'HasOneEditDataObjectExtension'
ChosenField:
  rtl: false
Select2Field:
  rtl: false
  use_v3: true
SexyPasswordField:
  show_password_constraints: true
  enable_show_hide: true
SimpleTinyMceField:
  plugins: 'autolink link lists hr anchor media emoticons'